name: build

on: push
jobs:
  start-kind:
    runs-on: actuated-2cpu-2gb
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup mirror
        uses: self-actuated/hub-mirror@master
      - name: get arkade
        uses: alexellis/setup-arkade@v1
      - name: get kubectl and kubectl
        uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kind: latest
      - name: Install Kubernetes kind
        run: |
          mkdir -p $HOME/.kube/
          kind create cluster --wait 300s
      - name: Wait until CoreDNS is ready
        run: |
          kubectl rollout status deploy/coredns -n kube-system --timeout=300s
      - name: Explore nodes
        run: kubectl get nodes -o wide
      - name: Explore pods
        run: kubectl get pod -A -o wide
      - name: Install ingress-nginx
        run: arkade install ingress-nginx

      # For debug and troubleshooting, always show the output of the kubelet
      # to find missing Kernel modules or errors in the system image 
      # configuration.
      - name: Show kubelet logs
        if: always()
        run: docker exec kind-control-plane journalctl -u kubelet
